steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'modern-stack/Dockerfile.cloud', '-t', 'gcr.io/${_PROJECT_ID}/community-dashboard:latest', 'modern-stack']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT_ID}/community-dashboard:latest']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'community-dashboard'
      - '--image'
      - 'gcr.io/${_PROJECT_ID}/community-dashboard:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '5'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--add-cloudsql-instances'
      - '${_PROJECT_ID}:${_REGION}:community-dashboard-db'
      - '--update-secrets'
      - 'DATABASE_URL=database-url:latest'
      - '--update-secrets'
      - 'NEXTAUTH_SECRET=nextauth-secret:latest'
      - '--update-secrets'
      - 'REDIS_URL=redis-url:latest'
      - '--update-secrets'
      - 'MATRIX_HOMESERVER_URL=matrix-homeserver-url:latest'
      - '--update-secrets'
      - 'MATRIX_ACCESS_TOKEN=matrix-access-token:latest'

images:
  - 'gcr.io/${_PROJECT_ID}/community-dashboard:latest'

timeout: '1800s'
options:
  logging: CLOUD_LOGGING_ONLY