services:
  streamlit-app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - AUTHENTIK_API_TOKEN=${AUTHENTIK_API_TOKEN}
      - MAIN_GROUP_ID=${MAIN_GROUP_ID}
      - BASE_DOMAIN=${BASE_DOMAIN}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - signal-cli

  db:
    image: postgres:15
    volumes:
      - ./app/db/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT:-5432}:5432" # Default to port 5432 if POSTGRES_PORT not set
      # it will still work on the new port 

  signal-cli:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal-cli
    environment:
      - MODE=json-rpc # Fastest mode with a persistent daemon process
      - SIGNAL_NUMBER=${SIGNAL_PHONE_NUMBER}
      # Optional improved settings
      - SIGNAL_CLI_CONFIG_DIR=/home/.local/share/signal-cli/
      - SWAGGER_HOST=${BASE_DOMAIN:-localhost}
      - SWAGGER_USE_HTTPS_AS_PREFERRED_SCHEME=true
      # Only add this if you're not handling receiving messages in your app
      # - AUTO_RECEIVE_SCHEDULE=*/15 * * * * # Check for messages every 15 minutes
    volumes:
      - ./signal-data:/home/.local/share/signal-cli # Persistent storage for signal data
    ports:
      - "${SIGNAL_PORT:-8080}:8080" # The REST API port
    restart: unless-stopped

volumes:
  postgres_data:
  signal-data:
