services:
  streamlit:
    build: .
    ports:
      - "${PORT:-8503}:8503"          # External port (configurable) : Internal port (fixed at 8503)
      - "${API_PORT:-5001}:5001"      # External port (configurable) : Internal port (fixed at 5001)
    volumes:
      - .:/app
      - /app/node_modules  # Prevent node_modules from being overwritten by volume mount
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1  # Enable unbuffered output
      - IN_DOCKER=true      # Indicate we're running in Docker
      - DB_HOST=db          # Explicitly set database host
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # When inside Docker network, always use the internal port 5432
      - POSTGRES_PORT=5432
      # Enhanced User Management API configuration
      - API_SECRET_KEY=${API_SECRET_KEY:-default-docker-api-key}
      - API_BASE_URL=http://localhost:5001
      - USE_REACT_FRONTEND=${USE_REACT_FRONTEND:-false}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8503 && curl -f http://localhost:5001/api/users/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5436}:5432" # POSTGRES_PORT is the external host port (default 5436), 5432 is the internal container port
      # Applications inside Docker should always connect to port 5432 via the internal Docker network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
