services:
  streamlit-app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - AUTHENTIK_API_TOKEN=${AUTHENTIK_API_TOKEN}
      - MAIN_GROUP_ID=${MAIN_GROUP_ID}
      - BASE_DOMAIN=${BASE_DOMAIN}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - ./app/db/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT:-5432}:5432" # Default to port 5432 if POSTGRES_PORT not set
      # it will still work on the new port 

volumes:
  postgres_data:
