"""Add ModeratorPermission model for granular permissions

Revision ID: e65a9fb7d618
Revises: 08fcd60b9198
Create Date: 2025-05-24 13:41:40.278328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65a9fb7d618'
down_revision = '08fcd60b9198'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 