steps:
  # Build the container image optimized for Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'cloud-deployment/docker/Dockerfile.cloudrun'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/community-dashboard:$COMMIT_SHA'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/community-dashboard:latest'
      - '.'
    timeout: 1200s
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/community-dashboard:$COMMIT_SHA'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/community-dashboard:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/community-dashboard:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080,SEED_DATABASE=true,CREATE_ADMIN=true'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:$_REGION:$_DB_INSTANCE_NAME'
      - '--update-secrets'
      - 'DATABASE_URL=database-url:latest'
      - '--update-secrets'
      - 'NEXTAUTH_SECRET=nextauth-secret:latest'
      - '--update-secrets'
      - 'DEFAULT_ADMIN_PASSWORD=admin-password:latest'
      - '--update-secrets'
      - 'MATRIX_HOMESERVER_URL=matrix-homeserver-url:latest'
      - '--update-secrets'
      - 'MATRIX_ACCESS_TOKEN=matrix-access-token:latest'
      - '--update-secrets'
      - 'REDIS_URL=redis-url:latest'
      - '--vpc-connector'
      - 'projects/$PROJECT_ID/locations/$_REGION/connectors/$_VPC_CONNECTOR'
      - '--ingress'
      - 'all'
      - '--execution-environment'
      - 'gen2'
    timeout: 900s

# Substitution variables (can be overridden)
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'community-dashboard'
  _ARTIFACT_REPO: 'community-dashboard'
  _DB_INSTANCE_NAME: 'community-dashboard-db'
  _VPC_CONNECTOR: 'dashboard-connector'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

# Build timeout
timeout: 2400s
