"""Add last_synced column to matrix_rooms

Revision ID: 67dd689621e4
Revises: e65a9fb7d618
Create Date: 2025-05-26 02:31:05.061979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67dd689621e4'
down_revision = 'e65a9fb7d618'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrix_rooms', sa.Column('last_synced', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matrix_rooms', 'last_synced')
    # ### end Alembic commands ### 